name: Bump NPM version

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (one of): patch, minor, major, prepatch, preminor, premajor, prerelease'
        required: true

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPLOYER_RELEASE_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Git configuration
        run: |
          git config user.name "Leukeleu Deployer"
          git config user.email "deployer@leukeleu.nl"

      - name: Bump version
        run: npm version ${{ github.event.inputs.release-type }}

      - name: Push changes to repository
        run: git push && git push --tags
